test: updated .releaserc to resolve release issue.
splunk/pytest-splunk-addon pull request #444
Opened 2021-11-03 04:46 UTC by dwijesh-shah-crest

2021-11-03 09:27 UTC, arys-splunk requested changes
1. Can you please change the conventional commit to "ci" instead of "test" and squash 2 commits into 1?
2. Can you please sign CLA and COC?

2021-11-03 09:58 UTC, dwijesh-shah-crest commented
I have read the CLA Document and I hereby sign the CLA

I have read the Code of Conduct and I hereby accept the Terms

2021-11-03 10:01 UTC, dwijesh-shah-crest commented
I have read the Code of Conduct and I hereby accept the Terms

2021-11-03 10:26 UTC, arys-splunk approved these changes
LGTM

I've tested it with regex101.com and it seems to find only 1 occurrence of version.

2021-11-03 10:40 UTC, merged

2021-11-04 12:10 UTC, rfaircloth-splunk commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- `v1.10.0`
- [GitHub release](https://github.com/splunk/pytest-splunk-addon/releases/tag/v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: