fix: checkpoint cef format issue
splunk/pytest-splunk-addon pull request #597
Opened 2022-04-01 21:01 UTC by nandinivij

2022-04-01 21:29 UTC, nandinivij commented
@dhruvp-crest can you please verify the above with checkpoint TA

2022-04-02 01:31 UTC, dhruvp-crest submitted a review, later dismissed

2022-04-02 09:35 UTC, arys-splunk requested changes
Can you please add test for this fix?

2022-04-05 09:33 UTC, arys-splunk approved these changes
The test we have in `tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py` is not that clean and I have hard time understanding what is being tested, but PR actually fixes the issue, so I am fine merging this.

2022-04-05 09:34 UTC, merged

2022-04-05 10:06 UTC, srv-rr-github-token commented
:tada: This PR is included in version 3.0.4 :tada:

The release is available on:
- `v3.0.4`
- [GitHub release](https://github.com/splunk/pytest-splunk-addon/releases/tag/v3.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: